version: "3.9"
services:
  proxy:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  todayhouse:
    image: nginx
    ports:
      - "80"
    volumes:
      - ./todayhouse:/source
      - ./default.conf:/etc/nginx/conf.d/default.conf
  excel:
    image: nginx
    ports:
      - "80"
    volumes:
      - ./excel:/source
      - ./default.conf:/etc/nginx/conf.d/default.conf
  msi:
    image: nginx
    ports:
      - "80"
    volumes:
      - ./msi:/source
      - ./default.conf:/etc/nginx/conf.d/default.conf
